# 导入节点映射
from .janus_nodes import NODE_CLASS_MAPPINGS as JANUS_NODES
from .janus_nodes import NODE_DISPLAY_NAME_MAPPINGS as JANUS_DISPLAY_NAMES
from .janus_chat import NODE_CLASS_MAPPINGS as CHAT_NODES
from .janus_chat import NODE_DISPLAY_NAME_MAPPINGS as CHAT_DISPLAY_NAMES

# 合并映射
NODE_CLASS_MAPPINGS = {
    **JANUS_NODES,
    **CHAT_NODES
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **JANUS_DISPLAY_NAMES,
    **CHAT_DISPLAY_NAMES
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS'] 